version: '3.9'

services:
  web:
    build: .
    container_name: sign-language-translator
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./modelnet_model.h5:/app/modelnet_model.h5
    environment:
      - FLASK_ENV=production
    restart: always
